[package]
name = "tideline"
version = "0.1.0"
description = "A Tauri App"
authors = ["you"]
edition.workspace = true
rust-version.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
# The `_lib` suffix may seem redundant but it is necessary
# to make the lib name unique and wouldn't conflict with the bin name.
# This seems to be only an issue on Windows, see https://github.com/rust-lang/cargo/issues/8519
name = "tideline_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[features]
default = ["custom-protocol", "bundled-plugins"]
custom-protocol = ["tauri/custom-protocol"]
bundled-plugins = []

[dependencies]
tideline-core = { workspace = true }
tideline-sdk = { workspace = true }
tideline-host = { workspace = true }
tauri = { version = "2", features = ["tray-icon"] }
tauri-plugin-opener = "2"
tauri-plugin-global-shortcut = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
libpulse-binding = "2.28"
libpulse-simple-binding = "2.28"
freedesktop-icons = "0.4"
base64 = "0.22"
evdev = "0.13"
ashpd = { version = "0.13", default-features = false, features = ["tokio", "global_shortcuts"] }
zbus = { version = "5", default-features = false, features = ["tokio"] }
futures-util = "0.3"
tokio = { version = "1", features = ["macros", "process", "io-util", "time"] }
mime_guess = "2"
dirs = "5"
notify-rust = "4"
async-trait = { workspace = true }

