pub mod directive;
pub mod serialize;
pub mod topology;

use crate::config_io::{pipewire_conf_dir, pulse_conf_dir, slug, wireplumber_conf_dir};
use crate::model::{AppConfig, ChannelCfg, ChannelKind, Mix};
use std::fs;

pub const TIDELINE_PIPEWIRE_FILE: &str = "50-tideline.conf";
pub const TIDELINE_PULSE_ROUTING_FILE: &str = "50-tideline-routing.conf";
pub const TIDELINE_WIREPLUMBER_LEGACY_FILE: &str = "50-tideline-routing.conf";
pub const LEGACY_PIPEWIRE_FILES: &[&str] = &["10-virtual-sinks.conf", "20-loopbacks.conf"];

pub fn mix_playback_node(ch: &ChannelCfg, mix: &Mix, sink_idx: usize) -> String {
    format!("playback.{}-{}-{}", slug(&ch.name), mix.id, sink_idx)
}

pub fn mix_capture_node(ch: &ChannelCfg, mix: &Mix, sink_idx: usize) -> String {
    format!("capture.{}-{}-{}", slug(&ch.name), mix.id, sink_idx)
}

pub fn sink_node_for_channel(ch: &ChannelCfg) -> String {
    ch.hp_node
        .strip_prefix("playback.")
        .and_then(|s| s.strip_suffix("-hp"))
        .map(|s| format!("sink.{}", s))
        .unwrap_or_else(|| format!("sink.{}", slug(&ch.name)))
}

pub fn generate_pipewire_config(cfg: &AppConfig) -> Result<String, String> {
    if cfg.mixes.is_empty() {
        return Err("At least one mix is required. Open the Mixes view and add one.".into());
    }
    if cfg.channels.is_empty() {
        return Err("At least one channel is required.".into());
    }

    let directives = topology::build_base_topology(cfg);
    Ok(serialize::serialize_directives(&directives))
}

pub fn generate_app_routing_config(cfg: &AppConfig) -> String {
    let mut out = String::new();
    out.push_str("# Generated by Tideline — do not edit manually\n\n");
    out.push_str("pulse.rules = [\n");
    for ch in &cfg.channels {
        if ch.kind != ChannelKind::Output { continue; }
        if ch.programs.is_empty() { continue; }
        let sink_name = sink_node_for_channel(ch);
        out.push_str("  {\n    matches = [\n");
        for prog in &ch.programs {
            out.push_str(&format!("      {{ application.process.binary = \"{}\" }}\n", prog));
        }
        out.push_str("    ]\n");
        out.push_str(&format!("    actions = {{ update-props = {{ target.object = \"{}\" }} }}\n", sink_name));
        out.push_str("  }\n");
    }
    out.push_str("]\n");
    out
}

pub fn write_app_routing(cfg: &AppConfig) -> Result<(), String> {
    let legacy = wireplumber_conf_dir().join(TIDELINE_WIREPLUMBER_LEGACY_FILE);
    if legacy.exists() {
        let _ = fs::remove_file(&legacy);
    }

    let dir = pulse_conf_dir();
    fs::create_dir_all(&dir).map_err(|e| e.to_string())?;
    let body = generate_app_routing_config(cfg);
    let target = dir.join(TIDELINE_PULSE_ROUTING_FILE);
    fs::write(&target, body).map_err(|e| e.to_string())
}

pub fn write_pipewire_conf(cfg: &AppConfig) -> Result<Vec<String>, String> {
    let body = generate_pipewire_config(cfg)?;

    let dir = pipewire_conf_dir();
    fs::create_dir_all(&dir).map_err(|e| e.to_string())?;

    let mut backed_up: Vec<String> = Vec::new();
    for legacy in LEGACY_PIPEWIRE_FILES {
        let path = dir.join(legacy);
        if path.exists() {
            let bak = dir.join(format!("{}.bak", legacy));
            if let Err(e) = fs::rename(&path, &bak) {
                return Err(format!("Failed to back up {}: {}", legacy, e));
            }
            backed_up.push((*legacy).to_string());
        }
    }

    let target = dir.join(TIDELINE_PIPEWIRE_FILE);
    fs::write(&target, body).map_err(|e| e.to_string())?;

    write_app_routing(cfg)?;
    Ok(backed_up)
}
