pub mod contribute;
pub mod directive;
pub mod serialize;
pub mod topology;

use crate::config_io::{pipewire_conf_dir, pulse_conf_dir, slug, wireplumber_conf_dir};
use crate::model::{AppConfig, ChannelCfg, ChannelKind, Mix};
use std::collections::HashSet;
use std::fs;

pub const TIDELINE_PIPEWIRE_FILE: &str = "50-tideline.conf";
pub const TIDELINE_PULSE_ROUTING_FILE: &str = "50-tideline-routing.conf";
pub const TIDELINE_WIREPLUMBER_LEGACY_FILE: &str = "50-tideline-routing.conf";
pub const LEGACY_PIPEWIRE_FILES: &[&str] = &["10-virtual-sinks.conf", "20-loopbacks.conf"];

pub fn mix_playback_node(ch: &ChannelCfg, mix: &Mix, sink_idx: usize) -> String {
    format!("playback.{}-{}-{}", slug(&ch.name), mix.id, sink_idx)
}

pub fn mix_capture_node(ch: &ChannelCfg, mix: &Mix, sink_idx: usize) -> String {
    format!("capture.{}-{}-{}", slug(&ch.name), mix.id, sink_idx)
}

pub fn sink_node_for_channel(ch: &ChannelCfg) -> String {
    ch.hp_node
        .strip_prefix("playback.")
        .and_then(|s| s.strip_suffix("-hp"))
        .map(|s| format!("sink.{}", s))
        .unwrap_or_else(|| format!("sink.{}", slug(&ch.name)))
}

/// Persistent virtual-source endpoint for a PhysicalInput channel.
/// Apps (e.g. Discord) record from this — it appears as "{name} - FX"
/// in their device selectors. Created in base topology with role
/// `physical_input_virtual_source` so the effects-plugin contributor
/// won't destroy it when toggling the chain.
pub fn fx_source_node(ch: &ChannelCfg) -> String {
    format!("fx_source.{}", slug(&ch.name))
}

/// Two-phase pipeline: build base topology (filtered by per-mix mute),
/// fold each contribution batch in order, then serialize. An empty
/// `contributions` slice yields the base topology unchanged.
pub fn build_pipewire_conf(
    cfg: &AppConfig,
    contributions: &[Vec<directive::PipewireDirective>],
    mix_mutes: &[directive::MixMuteEntry],
    available_sinks: Option<&HashSet<String>>,
) -> String {
    let mut directives = topology::build_base_topology(cfg, mix_mutes, available_sinks);
    for batch in contributions {
        directives = contribute::apply_contribution(directives, batch);
    }
    if let Some(available) = available_sinks {
        directives = drop_loopbacks_to_absent_sinks(cfg, directives, available);
    }
    serialize::serialize_directives(&directives)
}

/// The `playback.props` `target.object` of a loopback, if it has one.
fn playback_target(d: &directive::PipewireDirective) -> Option<&str> {
    let directive::PipewireDirective::LoadModule { args, .. } = d else {
        return None;
    };
    let props = args.iter().find_map(|(k, v)| match (k.as_str(), v) {
        ("playback.props", directive::ArgValue::Group(props)) => Some(props),
        _ => None,
    })?;
    props.iter().find_map(|(k, v)| match (k.as_str(), v) {
        ("target.object", directive::ArgValue::Quoted(s)) => Some(s.as_str()),
        _ => None,
    })
}

/// Base topology filters its own mix targets, but plugin contributors build
/// loopbacks too and cant see the sink list from their own process. This is
/// the one chokepoint every directive passes through, so it catches them all.
///
/// Only names that appear in some `mix.sinks` are eligible to be dropped.
/// Internal targets (`fx_source.*`, the per-channel JACK clients) are never
/// real sinks and would otherwise all get culled.
fn drop_loopbacks_to_absent_sinks(
    cfg: &AppConfig,
    directives: Vec<directive::PipewireDirective>,
    available: &HashSet<String>,
) -> Vec<directive::PipewireDirective> {
    let configured: HashSet<&str> = cfg
        .mixes
        .iter()
        .flat_map(|m| m.sinks.iter().map(|s| s.as_str()))
        .collect();

    directives
        .into_iter()
        .filter(|d| match playback_target(d) {
            Some(t) => !configured.contains(t) || available.contains(t),
            None => true,
        })
        .collect()
}

pub fn generate_pipewire_config(
    cfg: &AppConfig,
    available_sinks: Option<&HashSet<String>>,
) -> Result<String, String> {
    if cfg.mixes.is_empty() {
        return Err("At least one mix is required. Open the Mixes view and add one.".into());
    }
    if cfg.channels.is_empty() {
        return Err("At least one channel is required.".into());
    }

    Ok(build_pipewire_conf(cfg, &[], &[], available_sinks))
}

pub fn generate_app_routing_config(cfg: &AppConfig) -> String {
    let mut out = String::new();
    out.push_str("# Generated by Tideline — do not edit manually\n\n");
    out.push_str("pulse.rules = [\n");
    for ch in &cfg.channels {
        if ch.kind != ChannelKind::Output {
            continue;
        }
        if ch.programs.is_empty() {
            continue;
        }
        let sink_name = sink_node_for_channel(ch);
        out.push_str("  {\n    matches = [\n");
        for prog in &ch.programs {
            out.push_str(&format!(
                "      {{ application.process.binary = \"{}\" }}\n",
                prog
            ));
        }
        out.push_str("    ]\n");
        out.push_str(&format!(
            "    actions = {{ update-props = {{ target.object = \"{}\" }} }}\n",
            sink_name
        ));
        out.push_str("  }\n");
    }
    out.push_str("]\n");
    out
}

pub fn write_app_routing(cfg: &AppConfig) -> Result<(), String> {
    let legacy = wireplumber_conf_dir().join(TIDELINE_WIREPLUMBER_LEGACY_FILE);
    if legacy.exists() {
        let _ = fs::remove_file(&legacy);
    }

    let dir = pulse_conf_dir();
    fs::create_dir_all(&dir).map_err(|e| e.to_string())?;
    let body = generate_app_routing_config(cfg);
    let target = dir.join(TIDELINE_PULSE_ROUTING_FILE);
    fs::write(&target, body).map_err(|e| e.to_string())
}

pub fn write_pipewire_conf(
    cfg: &AppConfig,
    available_sinks: Option<&HashSet<String>>,
) -> Result<Vec<String>, String> {
    write_pipewire_conf_with_contributions(cfg, &[], &[], available_sinks)
}

pub fn write_pipewire_conf_with_contributions(
    cfg: &AppConfig,
    contributions: &[Vec<directive::PipewireDirective>],
    mix_mutes: &[directive::MixMuteEntry],
    available_sinks: Option<&HashSet<String>>,
) -> Result<Vec<String>, String> {
    if cfg.mixes.is_empty() {
        return Err("At least one mix is required. Open the Mixes view and add one.".into());
    }
    if cfg.channels.is_empty() {
        return Err("At least one channel is required.".into());
    }
    let body = build_pipewire_conf(cfg, contributions, mix_mutes, available_sinks);

    let dir = pipewire_conf_dir();
    fs::create_dir_all(&dir).map_err(|e| e.to_string())?;

    let mut backed_up: Vec<String> = Vec::new();
    for legacy in LEGACY_PIPEWIRE_FILES {
        let path = dir.join(legacy);
        if path.exists() {
            let bak = dir.join(format!("{}.bak", legacy));
            if let Err(e) = fs::rename(&path, &bak) {
                return Err(format!("Failed to back up {}: {}", legacy, e));
            }
            backed_up.push((*legacy).to_string());
        }
    }

    let target = dir.join(TIDELINE_PIPEWIRE_FILE);
    fs::write(&target, body).map_err(|e| e.to_string())?;

    write_app_routing(cfg)?;
    Ok(backed_up)
}
