//! Serialize `PipewireDirective`s into the textual conf format that PipeWire
//! consumes. Produces byte-equivalent output to the legacy string-pushing
//! generator.
//!
//! Note (Wave 2 / B3): `RewireableTag`s carried on directives are intentionally
//! NOT rendered as comments yet. The plan calls for `# tideline-rewireable: ...`
//! comment lines once plugin contributions can flip the format forward; until
//! then the golden conf is the authoritative pin and tags stay invisible.

use super::directive::{ArgValue, LoadModuleHeader, PipewireDirective};

const HEADER: &str = "# Generated by Tideline — do not edit manually\n\n";

pub fn serialize_directives(directives: &[PipewireDirective]) -> String {
    let mut out = String::new();
    out.push_str(HEADER);

    out.push_str("context.objects = [\n");
    for d in directives {
        if let PipewireDirective::LoadModule {
            header: LoadModuleHeader::Factory(factory),
            args,
            ..
        } = d
        {
            out.push_str("    { factory = ");
            out.push_str(factory);
            out.push_str("  args = ");
            write_inline_args(&mut out, args);
            out.push_str(" }\n");
        }
    }
    out.push_str("]\n\n");

    out.push_str("context.modules = [\n");
    for d in directives {
        if let PipewireDirective::LoadModule {
            header: LoadModuleHeader::Named(module),
            args,
            ..
        } = d
        {
            let multiline = args.iter().any(|(_, v)| matches!(v, ArgValue::Group(_)));
            out.push_str("    { name = ");
            out.push_str(module);
            if multiline {
                out.push_str("  args = {\n");
                for (k, v) in args {
                    out.push_str("        ");
                    out.push_str(k);
                    out.push_str(" = ");
                    write_value(&mut out, v);
                    out.push('\n');
                }
                out.push_str("    } }\n");
            } else {
                out.push_str("  args = ");
                write_inline_args(&mut out, args);
                out.push_str(" }\n");
            }
        }
    }
    out.push_str("]\n");

    out
}

/// Writes an arg list inline as `{ k1 = v1  k2 = v2 ... }` (with the leading
/// `{` and trailing `}`, surrounded by a single inner space).
fn write_inline_args(out: &mut String, args: &[(String, ArgValue)]) {
    out.push('{');
    for (k, v) in args {
        out.push(' ');
        out.push_str(k);
        out.push_str(" = ");
        write_value(out, v);
        out.push(' ');
    }
    out.push('}');
}

fn write_value(out: &mut String, v: &ArgValue) {
    match v {
        ArgValue::Literal(s) => out.push_str(s),
        ArgValue::Quoted(s) => {
            out.push('"');
            out.push_str(s);
            out.push('"');
        }
        ArgValue::Group(items) => write_inline_args(out, items),
    }
}
