//! Raw FFI bindings to libcarla_standalone2 generated by bindgen at build time.
//!
//! See `build.rs` for the bindgen invocation and allowlist.

#![allow(
    non_camel_case_types,
    non_snake_case,
    non_upper_case_globals,
    dead_code,
    clippy::all
)]

include!(concat!(env!("OUT_DIR"), "/bindings.rs"));
